### ISSUE TITLE
Issues with the latest version of Gitlab (7.12.0)

### ISSUE THREAD

**Issue by adamlc** [sameersbn/docker-laboard#2]
Just thought I'd give this image an spin on top of your gitlab image (great btw) and there seems to be a few issues with latest gitlab. Might just be a case of a new release?

Edit: Looking round their repo, doesn't seem to be much activity, so probably just broken!

**Comment by sameersbn** [comment]
@adamlc probably. the builds have already started breaking for some reason.

**Comment by adamlc** [comment]
Looks like theres activity in the oauth branch, hopefully the issues are being worked on their end :)
